### ISSUE TITLE
Feature Request one-tailed

### ISSUE THREAD

**Issue by lburleigh** [IndrajeetPatil/statsExpressions#10]
This package is absolutely wonderful and makes some amazing plots! It would be awesome if it could also report one-tailed t-tests, rather than two-tailed. 

Thank you so much for this package!

**Comment by IndrajeetPatil** [comment]
I have decided against supporting this, since an argument of this type won't be valid across all analyses types currently supported in the package (e.g., robust and Bayesian statistics).

**Comment by madebyafox** [comment]
I would second @lburleigh request for this feature. Although it may not be valid across some types of analyses supported, it is a (very) common variant of t-tests, and not having it means that the package can't be used for these comparisons. Otherwise, I adore this package, and am grateful for your hard work and support @IndrajeetPatil !
