### ISSUE TITLE
Necessity of patch-level version bumps in dependencies

### ISSUE THREAD

**Issue by mfansler** [IndrajeetPatil/statsExpressions#252]
This package frequently bumps patch-level versions in dependencies. Is this actually necessary?

For instance, [`dplyr` v1.1.2 -> v1.1.3](https://github.com/tidyverse/dplyr/releases/tag/v1.1.3) doesn't appear to add any functionality. What is the reason that this package *requires* it?

**Comment by IndrajeetPatil** [comment]
Technically, no. But most of the key dependencies of _statsExpressions_ (viz. packages from _tidyverse_ and _easystats_ ecosystems) are under active development with relatively rapidly evolving API. 

Therefore, from time-to-time, I bump the needed dep versions to make sure that the end users:
-  have the latest features available to them
- don't see any unwanted messages/warnings because I am using older API from these dependencies

This will naturally come to a halt as the development pace for these dependencies slows down.
