### ISSUE TITLE
Select specific stats

### ISSUE THREAD

**Issue by kwakuduahc1** [IndrajeetPatil/statsExpressions#37]
Hello,

Is there a way to do a specific test, e.g. just the chi-squared test without the Crammer V?

Many thanks.

**Comment by IndrajeetPatil** [comment]
Unfortunately, this is currently not possible and I am not sure if this will ever be supported since all expressions try to follow a specific template: 

![](https://github.com/IndrajeetPatil/ggstatsplot/blob/master/man/figures/stats_reporting_format.png)

That said you can always adapt the returned expression to your need by deleting certain parts of the expression. 

Maybe I can add an example to the documentation to show how to do this.

**Comment by IndrajeetPatil** [comment]
Unfortunately, this is currently not possible and I am not sure if this will ever be supported since all expressions try to follow a specific template: 

![](https://github.com/IndrajeetPatil/ggstatsplot/blob/master/man/figures/stats_reporting_format.png)

That said you can always adapt the returned expression to your need by deleting certain parts of the expression. 

Maybe I can add an example to the documentation to show how to do this.

**Comment by kwakuduahc1** [comment]
Many thanks.

**Comment by IndrajeetPatil** [comment]
Here is an example:

```r
# setup
set.seed(123)
library(ggplot2)
library(statsExpressions)

# extracting subtitle
(res_expr <- expr_anova_parametric(iris, Species, Sepal.Length, var.equal = TRUE))
#> paste(NULL, italic("F")["Fisher"], "(", "2", ",", "147", ") = ", 
#>     "119.26", ", ", italic("p"), " = ", "1.67e-31", ", ", widehat(omega["p"]^2), 
#>     " = ", "0.61", ", CI"["95%"], " [", "0.52", ", ", "0.68", 
#>     "]", ", ", italic("n")["obs"], " = ", 150L)

# adapting the details to your liking
ggplot(iris, aes(x = Species, y = Sepal.Length)) +
  geom_boxplot() +
  labs(subtitle = ggplot2::expr(paste(
    NULL, italic("F"), "(", "2",
    ",", "147", ") = ", "119.26", ", ",
    italic("p"), " = ", "1.67e-31"
  )))
```

![image](https://user-images.githubusercontent.com/11330453/95092677-3a1d0a00-0728-11eb-9dba-1699269e34de.png)

**Comment by kwakuduahc1** [comment]
Many thanks.
