### ISSUE TITLE
Customisation of Subtitle Formatting

### ISSUE THREAD

**Issue by DarioS** [IndrajeetPatil/statsExpressions#82]
Could it be easier in future to customise the subtitle formatting style? For example,

![image](https://user-images.githubusercontent.com/631218/112082388-62ff6180-8bd9-11eb-9952-34ce630acbbb.png)

I would like to have the test statistic on linear scale rather than log scale (most texts use linear scale) and p-value shown in format

![image](https://user-images.githubusercontent.com/631218/112082341-48c58380-8bd9-11eb-9c49-9210ec3a679e.png)

Also, isn't it commonly known as the U test? I wonder why W is used for the test statistic.

**Comment by IndrajeetPatil** [comment]
> Could it be easier in future to customise the subtitle formatting style? 

Probably. Although such fine control would require adding a lot of arguments, which I am not too keen on doing that.

For now, you can just adjust the expressions to your liking via `statsExpressions`

``` r
library(statsExpressions)
sub <- two_sample_test(mtcars, am, wt, type = "np")

sub$expression
#> [[1]]
#> paste("log"["e"](italic("W")["Mann-Whitney"]), " = ", "5.44", 
#>     ", ", italic("p"), " = ", "4.35e-05", ", ", widehat(italic("r"))["biserial"]^"rank", 
#>     " = ", "0.87", ", CI"["95%"], " [", "0.66", ", ", "1.00", 
#>     "]", ", ", italic("n")["obs"], " = ", "32")

library(ggstatsplot)
library(ggplot2)

# modify the expression to your liking
ggbetweenstats(mtcars, am, wt) +
  labs(subtitle = ggplot2::expr(paste(
    italic("W")["Mann-Whitney"], " = ", "230.44",
    ", ", italic("p"), " = ", "4.35", " X ", "10"^"-05", ", ", widehat(italic("r"))["biserial"]^"rank",
    " = ", "0.87", ", CI"["95%"], " [", "0.68", ", ", "1.00",
    "]", ", ", italic("n")["obs"], " = ", "32"
  )))
```

![](https://i.imgur.com/fBJsS2h.png)

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup> 

> Also, isn't it commonly known as the U test? I wonder why W is used for the test statistic.

This is because *W* is what `stats::wilcox.test` returns. And, it's not just `ggstatsplot`, you look at output from other software programs (e.g., JASP), you will see that they also report the same:

<img width="729" alt="Screenshot 2021-03-23 at 08 06 34" src="https://user-images.githubusercontent.com/11330453/112107392-2d458300-8baf-11eb-96a5-95235b0a1c66.png">
